### PR TITLE
WP-13963 Discovery in progress for long time when given credentials are not working

### PR DESCRIPTION
**Pull request by jayma91**
Discovery in progress for long time when given credentials are not working
https://varicent.atlassian.net/browse/WP-13963

- reduced to 1 try and 15s timeout
- Discovery retry attempts: 2 (3 tries in total), each try will typically take around ~17s
image

### CODE REVIEW

**Review by rsantos-varicent — APPROVED** [review]

**Comment by sunil-varicent** [comment]
It seems like its still more than a min to show the error in UI, which I think is little slow for showing connection error.

Any findings on way to make step function not retry for certain types of exception from woker/tap?

**Comment by jayma91** [comment]
> It seems like its still more than a min to show the error in UI, which I think is little slow for showing connection error.
> 
> Any findings on way to make step function not retry for certain types of exception from woker/tap?

It seems possible to generate custom error in discoveryWorker and modify retry logics based on the custom error we generate. However, it was observed that most of connection error (wrong credentials, wrong host, etc) takes less than 2 seconds in to fail, so it will be approx ~ 10s for whole step function to fail. 
The only case it takes long enough is the actual time out error which can happen if 1) port number is wrong, 2) actual time out waiting for server response. It feels like it's worth to retry for case 2), but we cannot distinguish case 1) and 2) from the error message. 
Also, other db connectors or third party connectors would probably have similar issue for failed connection due to wrong config, meaning that we would need to add error handling code for connection errors (in importErrorParser.ts) to discoveryWorker.
@rsantos-varicent @sunil-varicent  Should we still look into adding code for generating custom error in discovery worker and modifying retry logic?

**Comment by rsantos-varicent** [comment]
i think it's useful controlling retries on the activity level, but it's not a priority right now
lets open a ticket for it and we'll put it on the queue

**Comment by sunil-varicent** [comment]
@rsantos-varicent On the note of errors during discovery and taking long time, error toast messages stays in UI for some seconds and disappear. So, we have to  keep on looking  at the screen to catch the error which is frustrating for user.  I think we need to do improve such cases. I created ticket for that long time ago, but did not get prioritized: https://varicent.atlassian.net/browse/WP-11503

**Review by sunil-varicent — APPROVED** [review]

**Pull request merged**
